title: Elena Stenina #your name (or website title) here
logo: "/images/logo.jfif?raw=true" # your photo (or logo) here
description: > #your text below (remove <br> elements if you don't need line breaks)

  <br><br>
  Hello! My name is Elena Stenina. I am Full-stuck Web Developer with 5 years experience. I love coding a lot. As a Web Developer, I enjoy using my obsessive attention to detail, my unequivocal love for making things, and my mission-driven work ethic to literally change the world. 
  <br><br>
  <a href="https://www.linkedin.com/in/elena-stenina-a54020a5/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-142998002-1 # your Google Analytics tracking ID here
